# Generated by Django 4.1.6 on 2023-07-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_roles_backups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='in_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
