# Generated by Django 4.2.3 on 2023-07-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_log_logs_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='logs',
            new_name='log',
        ),
    ]
