# Generated by Django 4.2.3 on 2023-07-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(max_length=50)),
            ],
        ),
    ]
