# Generated by Django 4.1.5 on 2023-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_tree_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('airline', models.CharField(max_length=50)),
                ('from_airport', models.CharField(max_length=50)),
                ('to_airport', models.CharField(max_length=50)),
                ('departure_date', models.DateTimeField(max_length=50)),
                ('arrival_date', models.DateTimeField(max_length=50)),
                ('seats', models.IntegerField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='credit',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='debit',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
