# Generated by Django 4.1.5 on 2023-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_flights_delete_customers_alter_accounts_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='flights',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
