# Generated by Django 4.1.5 on 2023-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_flights_notes_alter_flights_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField(max_length=100)),
                ('departure_date', models.DateTimeField(max_length=50)),
                ('arrival_date', models.DateTimeField(max_length=50)),
            ],
            options={
                'ordering': ['flight_id'],
            },
        ),
    ]
