# Generated by Django 4.1.5 on 2023-05-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_bookings_hotel_rooms_rooms_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out_date',
            field=models.DateField(max_length=50),
        ),
    ]
