# Generated by Django 4.2.3 on 2023-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_airlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlines',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
