# Generated by Django 4.1.5 on 2023-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_bookings_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateTimeField(max_length=50),
        ),
    ]
