# Generated by Django 4.2.3 on 2023-07-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_airports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airports',
            name='name',
        ),
        migrations.AddField(
            model_name='airports',
            name='city',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='code',
            field=models.CharField(default='', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
