# Generated by Django 4.1.5 on 2023-05-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_bookings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
    ]
