# Generated by Django 4.1.5 on 2023-05-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateField( max_length=50),
            preserve_default=False,
        ),
    ]
