# Generated by Django 4.1.5 on 2023-05-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_bookings_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='date',
            new_name='book_date',
        ),
    ]
