# Generated by Django 4.2.3 on 2023-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_flights_airline_alter_flights_from_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='airline',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flights',
            name='from_airport',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flights',
            name='to_airport',
            field=models.CharField(max_length=50),
        ),
    ]
