# Generated by Django 4.1.5 on 2023-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_date_bookings_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='book_date',
            field=models.DateTimeField(max_length=50),
        ),
    ]
