# Generated by Django 4.1.5 on 2023-05-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_bookings_book_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
