# Generated by Django 4.1.5 on 2023-05-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_delete_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField(max_length=50)),
                ('guest_name', models.CharField(max_length=50)),
                ('room_id', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('check_in_date', models.DateField(max_length=50)),
                ('check_out_date', models.DateField(max_length=50)),
                ('guests', models.IntegerField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
