# Generated by Django 4.2.3 on 2023-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_roles_flight_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_bookings',
            name='seats',
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='infants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='persons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='return_date',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
