# Generated by Django 4.1.5 on 2023-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(max_length=100)),
                ('date', models.DateField(max_length=50)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=50)),
                ('room_id', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('dates', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['hotel'],
            },
        ),
        migrations.DeleteModel(
            name='Hotel_rooms',
        ),
        migrations.DeleteModel(
            name='Rooms_dates',
        ),
    ]
