# Generated by Django 4.1.5 on 2023-05-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_room_dates_rooms_delete_hotel_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),

        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
