# Generated by Django 4.2.3 on 2023-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_flight_bookings_seats_flight_bookings_infants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_date',
            field=models.DateField(max_length=50),
        ),
    ]
