# Generated by Django 4.1.5 on 2023-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_rooms_id_alter_bookings_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='book_date',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='room_id',
            field=models.CharField(max_length=50),
        ),
    ]
