# Generated by Django 4.2.3 on 2023-08-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_flights_arrival_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_bookings',
            old_name='flight_code',
            new_name='go_flight_code',
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='back_flight_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
