# Generated by Django 4.1.5 on 2023-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_rename_book_date_bookings_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=50),
        ),
    ]
