# Generated by Django 4.2.3 on 2023-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_flight_bookings_back_flight_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_bookings',
            name='depart_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight_bookings',
            name='return_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
