# Generated by Django 4.1.5 on 2023-05-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_rooms_id_alter_rooms_room_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='bookings',
            name='hotel',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='dates',
            field=models.CharField(max_length=1000),
        ),
    ]
