# Generated by Django 4.2.3 on 2023-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_flight_bookings_depart_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_bookings',
            name='depart_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
