# Generated by Django 4.1.5 on 2023-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_rooms_options_bookings_hotel_alter_rooms_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='bookings',
            name='dates',
            field=models.CharField(default='  ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='room_type',
            field=models.CharField(default='  ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='guests',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(max_length=50),
        ),
    ]
