# Generated by Django 4.2.3 on 2023-08-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_flight_bookings_depart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_bookings',
            name='depart_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flight_bookings',
            name='return_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
