# Generated by Django 4.1.5 on 2023-05-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_bookings_check_in_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='booking_date',
            new_name='book_date',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
