# Generated by Django 4.2.3 on 2023-08-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_flight_bookings_depart_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
