# Generated by Django 4.2.3 on 2023-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_flights_available_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_bookings',
            old_name='go_flight_code',
            new_name='flight1_code',
        ),
        migrations.RenameField(
            model_name='flight_bookings',
            old_name='back_flight_code',
            new_name='flight1_date',
        ),
        migrations.RenameField(
            model_name='flight_bookings',
            old_name='depart_date',
            new_name='flight2_code',
        ),
        migrations.RenameField(
            model_name='flight_bookings',
            old_name='return_date',
            new_name='flight2_date',
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='flight3_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='flight3_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='flight4_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='flight4_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='flight5_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight_bookings',
            name='flight5_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
