# Generated by Django 4.1.5 on 2023-05-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_bookings_username_alter_bookings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='username',
        ),
    ]
