# Generated by Django 4.2.6 on 2024-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_rename_go_flight_code_flight_bookings_flight1_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': (['id'],)},
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['status'], name='backend_boo_status_b03f18_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['hotel'], name='backend_boo_hotel_301f64_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['room_type'], name='backend_boo_room_ty_314704_idx'),
        ),
    ]
