# Generated by Django 4.1.5 on 2023-05-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_bookings_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rooms',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_id'), name='unique_room_for_hotel'),
        ),
    ]
