# Generated by Django 4.1.5 on 2023-05-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_rooms_unique_room_for_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_buttons',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
