# Generated by Django 4.1.5 on 2023-05-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_rename_dates_rooms_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_dates',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room_dates',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.rooms'),
        ),
    ]
