# Generated by Django 4.1.5 on 2023-05-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_room_dates_date_alter_room_dates_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_dates',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.rooms', to_field='room_id'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
