# Generated by Django 4.1.5 on 2023-05-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_room_dates_room_id_alter_rooms_room_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rooms',
            name='unique_room_for_hotel',
        ),
        migrations.AlterField(
            model_name='room_dates',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=50),
        ),
    ]
