# Generated by Django 4.1.5 on 2023-05-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_remove_rooms_unique_room_for_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='guests',
        ),
        migrations.AddField(
            model_name='bookings',
            name='kids_names',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bookings',
            name='kids_number',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='bookings',
            name='persons_names',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='persons_number',
            field=models.IntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
