# Generated by Django 4.1.5 on 2023-05-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_remove_bookings_guest_name_remove_bookings_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='persons',
            field=models.IntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
