# Generated by Django 4.1.6 on 2023-05-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_rooms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='kids_ages',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
