# Generated by Django 4.1.6 on 2023-05-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_bookings_kids_ages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('allotment', models.IntegerField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='meals',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_categ',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hotels'),
        ),
    ]
