# Generated by Django 4.1.6 on 2023-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_hotels_rooms_meals_rooms_room_categ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='out_date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
