# Generated by Django 4.1.6 on 2023-06-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0047_bookings_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='kids_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='persons_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight_dates',
            name='flight_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='allotment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='persons',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=1000)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
