# Generated by Django 4.1.6 on 2023-06-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_alter_bookings_kids_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='roles',
        ),
        migrations.AddField(
            model_name='roles',
            name='available_hotels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='hotels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='hotels_report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
