# Generated by Django 4.1.6 on 2023-06-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_remove_roles_roles_roles_available_hotels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='available_hotels',
            new_name='available_hotel',
        ),
    ]
