# Generated by Django 4.1.6 on 2023-06-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_rename_available_hotels_roles_available_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='backups/')),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
    ]
