# Generated by Django 4.1.6 on 2023-06-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_backup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
