# Generated by Django 4.1.6 on 2023-06-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_delete_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='out_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
