# Generated by Django 4.2.3 on 2023-07-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airports',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='code',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='status',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='updated_on',
        ),
    ]
